export default {
	drawerSmallBlack: require('images/drawerSmallBlack.png'),
	searchSmallBlack: require('images/searchSmallBlack.png'),
	logoSmall: require('images/logoSmall.png'),
	sliderExample: require('images/sliderExample.png'),
	brandLogo1: require('images/brandLogo1.png'),
	brandLogo2: require('images/brandLogo2.png'),
	brandLogo3: require('images/brandLogo3.png'),
	brandLogo4: require('images/brandLogo4.png'),
	brandLogo1Active: require('images/brandLogo1Active.png'),
	brandLogo2Active: require('images/brandLogo2Active.png'),
	brandLogo3Active: require('images/brandLogo3Active.png'),
	brandLogo4Active: require('images/brandLogo4Active.png'),
	barcodeTabBarIcon: require('images/barcodeTabBarIcon.png'),
	couponTabBarIcon: require('images/couponTabBarIcon.png'),
	favouriteTabBarIcon: require('images/favouriteTabBarIcon.png'),
	cartTabBarIcon: require('images/cartTabBarIcon.png'),
	plusTabBarIcon: require('images/plusTabBarIcon.png'),
	exampleBigImage: require('images/exampleBigImage.png'),
}